### ISSUE TITLE
standardx presets en Espanol

### ISSUE THREAD

**Issue by brodybits** [aMarCruz/eslint-plugin-prettierx#2]
In <https://github.com/aMarCruz/eslint-plugin-prettierx#presets>:
> * **standardx**
> Este es el estilo StandardJS, pero personalizable, como lo hace standardx.

 (<https://github.com/aMarCruz/eslint-plugin-prettierx/blame/master/README.md#L161>)

**Comment by aMarCruz** [comment]
@brodybits he, already fixed in v0.2.1

Also, it have exlusions for popular plugins and a new, [special preset](https://github.com/aMarCruz/eslint-plugin-prettierx#bundle-presets), for the whole eslint-standardize bundle.

The Readme includes a table with the initial options of each preset.

Closing, thanks!
